/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/updates': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/** @description Check if updaes are available */
		post: operations['updates_post']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
}
export type webhooks = Record<string, never>
export interface components {
	schemas: never
	responses: never
	parameters: never
	requestBodies: never
	headers: never
	pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
	updates_post: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': {
					/** @description Unique identifier for the installation */
					id: string
					app: {
						/** @description Name of the application */
						name: string
						/** @description Current version of the application */
						version: string
						/** @description Full build number or identifier */
						build: string
					}
					os: {
						/** @description Operating system platform */
						platform: string
						/** @description System architecture */
						arch: string
						/** @description OS release version */
						release: string
					}
				}
			}
		}
		responses: {
			/** @description Default Response */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': {
						/** @description Update message */
						message: string
						/**
						 * Format: uri
						 * @description Download URL
						 */
						link?: string
					}
				}
			}
			/** @description Validation error */
			400: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': {
						/** @description HTTP status code */
						statusCode: number
						/** @description Error code */
						code?: string
						/** @description Error name */
						error: string
						/** @description Error message */
						message: string
					}
				}
			}
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': {
						/** @description HTTP status code */
						statusCode: number
						/** @description Error code */
						code?: string
						/** @description Error name */
						error: string
						/** @description Error message */
						message: string
					}
				}
			}
		}
	}
}
