/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/updates': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/** @description Check if updates are available */
		post: operations['updates_post']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/updates-old': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/** @description Check if updates are available (legacy endpoint) */
		post: operations['updates-old_post']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/companion/detailed-usage': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/** @description Report detailed usage information */
		post: operations['companion_detailed-usage_post']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/companion/old-metrics': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/** @description Legacy Api endpoint for detailed usage information */
		post: operations['companion_old-metrics_post']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
}
export type webhooks = Record<string, never>
export interface components {
	schemas: never
	responses: never
	parameters: never
	requestBodies: never
	headers: never
	pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
	updates_post: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': {
					/** @description Unique identifier for the installation */
					id: string
					app: {
						/** @description Name of the application */
						name: string
						/** @description Current version of the application */
						version: string
						/** @description Full build number or identifier */
						build: string
					}
					os: {
						/** @description Operating system platform */
						platform: string
						/** @description System architecture */
						arch: string
						/** @description OS release version */
						release: string
					}
				}
			}
		}
		responses: {
			/** @description Default Response */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': {
						/** @description Indicates if the check was successful, or should be retried later */
						ok: boolean
						/** @description Update message */
						message: string
						/** @description Additional message (Supported since Companion 4.2) */
						message2?: string
						/**
						 * Format: uri
						 * @description Download URL
						 */
						link?: string
					}
				}
			}
			/** @description Validation error */
			400: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': {
						/** @description HTTP status code */
						statusCode: number
						/** @description Error code */
						code?: string
						/** @description Error name */
						error: string
						/** @description Error message */
						message: string
					}
				}
			}
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': {
						/** @description HTTP status code */
						statusCode: number
						/** @description Error code */
						code?: string
						/** @description Error name */
						error: string
						/** @description Error message */
						message: string
					}
				}
			}
		}
	}
	'updates-old_post': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': {
					/** @description Unique identifier for the installation */
					id: string
					/**
					 * @description Name of the application
					 * @enum {string}
					 */
					app_name: 'companion'
					/** @description Current version of the application */
					app_version: string
					/** @description Full build number or identifier */
					app_build: string
					/** @description Operating system platform */
					platform: string
					/** @description System architecture */
					arch: string
					/** @description OS release version */
					release: string
					tz?: unknown
					cpus?: unknown
					type?: unknown
				}
			}
		}
		responses: {
			/** @description Default Response */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': {
						/** @description Update message */
						message: string
						/**
						 * Format: uri
						 * @description Download URL
						 */
						link?: string
					}
				}
			}
			/** @description Validation error */
			400: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': {
						/** @description HTTP status code */
						statusCode: number
						/** @description Error code */
						code?: string
						/** @description Error name */
						error: string
						/** @description Error message */
						message: string
					}
				}
			}
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': {
						/** @description HTTP status code */
						statusCode: number
						/** @description Error code */
						code?: string
						/** @description Error name */
						error: string
						/** @description Error message */
						message: string
					}
				}
			}
		}
	}
	'companion_detailed-usage_post': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': {
					/** @description Unique identifier for the installation */
					id: string
					app: {
						/** @description Name of the application */
						name: string
						/** @description Current version of the application */
						version: string
						/** @description Full build number or identifier */
						build: string
					}
					os: {
						/** @description Operating system platform */
						platform: string
						/** @description System architecture */
						arch: string
						/** @description OS release version */
						release: string
					}
					/** @description Uptime of the application in seconds */
					uptime: number
					/** @description List of setup surfaces */
					surfaces: {
						/** @description Type of surface module used (eg elgato-stream-deck, loupedeck */
						moduleId: string
						/** @description Unique identifier for the surface (eg serial number) */
						id: string
						/** @description Human-readable description of the surface (eg Stream Deck XL) */
						description: string
					}[]
					/** @description List of setup connections */
					connections: {
						/** @description Type of connection module used (eg bmd-atem, studiocoast-vmix) */
						moduleId: string
						/** @description Map of connection versions to count of instances */
						counts: {
							[key: string]: number
						}
					}[]
					/** @description Feature usage details */
					features: {
						/** @description Indicates if the server is bound to loopback only */
						isBoundToLoopback: boolean
						/** @description Indicates if an admin password is set */
						hasAdminPassword: boolean
						/** @description Indicates if pincode lockout is enabled */
						hasPincodeLockout: boolean
						/** @description Indicates if cloud features are enabled */
						cloudEnabled: boolean
						/** @description Indicates if HTTPS is enabled */
						httpsEnabled: boolean
						/** @description Indicates if TCP protocol is enabled */
						tcpEnabled: boolean
						/** @description Indicates if deprecated TCP protocol is enabled */
						tcpDeprecatedEnabled: boolean
						/** @description Indicates if UDP protocol is enabled */
						udpEnabled: boolean
						/** @description Indicates if deprecated UDP protocol is enabled */
						udpDeprecatedEnabled: boolean
						/** @description Indicates if OSC protocol is enabled */
						oscEnabled: boolean
						/** @description Indicates if deprecated OSC protocol is enabled */
						oscDeprecatedEnabled: boolean
						/** @description Indicates if RossTalk protocol is enabled */
						rossTalkEnabled: boolean
						/** @description Indicates if Ember+ protocol is enabled */
						emberPlusEnabled: boolean
						/** @description Indicates if Art-Net protocol is enabled */
						artnetEnabled: boolean
						/** @description Number of active connections configured */
						connectionCount: number
						/** @description Number of pages configured */
						pageCount: number
						/** @description Number of buttons configured */
						buttonCount: number
						/** @description Number of triggers configured */
						triggerCount: number
						/** @description Number of surface groups configured */
						surfaceGroupCount: number
						/** @description Number of custom variables configured */
						customVariableCount: number
						/** @description Number of expression variables configured */
						expressionVariableCount: number
						/** @description Grid size details */
						gridSize: {
							/** @description Minimum grid column used */
							minCol: number
							/** @description Maximum grid column used */
							maxCol: number
							/** @description Minimum grid row used */
							minRow: number
							/** @description Maximum grid row used */
							maxRow: number
						}
						/** @description Number of connected satellite clients */
						connectedSatellites: number
					}
				}
			}
		}
		responses: {
			/** @description Default Response */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': {
						/** @description Indicates if the report was received successfully */
						ok: boolean
					}
				}
			}
			/** @description Validation error */
			400: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': {
						/** @description HTTP status code */
						statusCode: number
						/** @description Error code */
						code?: string
						/** @description Error name */
						error: string
						/** @description Error message */
						message: string
					}
				}
			}
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': {
						/** @description HTTP status code */
						statusCode: number
						/** @description Error code */
						code?: string
						/** @description Error name */
						error: string
						/** @description Error message */
						message: string
					}
				}
			}
		}
	}
	'companion_old-metrics_post': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: {
			content: {
				'application/json': unknown
			}
		}
		responses: {
			/** @description Default Response */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': {
						/** @description Indicates if the report was received successfully */
						ok: boolean
					}
				}
			}
			/** @description Validation error */
			400: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': {
						/** @description HTTP status code */
						statusCode: number
						/** @description Error code */
						code?: string
						/** @description Error name */
						error: string
						/** @description Error message */
						message: string
					}
				}
			}
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': {
						/** @description HTTP status code */
						statusCode: number
						/** @description Error code */
						code?: string
						/** @description Error name */
						error: string
						/** @description Error message */
						message: string
					}
				}
			}
		}
	}
}
