/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/v1/modules/package': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		/**
		 * Submit a built module package
		 * @description Submit a built module package
		 */
		put: operations['putModulePackage']
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/v1/website/connections': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Get a list of all published connections
		 * @description Get a list of all published connections
		 */
		get: operations['getWebsiteConnections']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/v1/website/connections/featured': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Get a list of featured connections
		 * @description Get a list of featured connections
		 */
		get: operations['getWebsiteFeaturedConnections']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/v1/companion/modules/{moduleType}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Get a list of all published modules
		 * @description Get a list of all published modules
		 */
		get: operations['getCompanionModules']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/v1/companion/modules/{moduleType}/{moduleName}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Get published versions of a module
		 * @description Get published versions of a module
		 */
		get: operations['getCompanionModuleVersions']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/v1/buttons/modules/{moduleType}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Get a list of all published modules
		 * @description Get a list of all published modules
		 */
		get: operations['getButtonsModules']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/v1/buttons/modules/{moduleType}/{moduleName}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Get published versions of a module
		 * @description Get published versions of a module
		 */
		get: operations['getButtonsModuleVersions']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/v1/public/modules/{moduleType}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Get a list of all modules
		 * @description Get a list of all modules of a given type, with basic info for listing
		 */
		get: operations['getPublicModules']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/v1/public/modules/{moduleType}/{moduleName}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Get detailed info about a module
		 * @description Get detailed information about a specific module, including tags, successor/predecessor info, images, etc.
		 */
		get: operations['getPublicModuleDetails']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/v1/public/modules/{moduleType}/{moduleName}/versions': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Get versions of a module
		 * @description Get all versions of a specific module, including published and unpublished
		 */
		get: operations['getPublicModuleVersions']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/v1/public/stats': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Get portal-wide statistics
		 * @description Get aggregate counts across the portal (modules, published versions, developers) for display on the homepage
		 */
		get: operations['getPublicStats']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/v1/modules-pending-review': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Get a list of module versions pending review
		 * @description Get a list of all module versions that are currently pending review, across all module types
		 */
		get: operations['getModulesPendingReview']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/v1/team/modules-pending-review': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Get module versions pending review with reviewer info
		 * @description Returns a list of all module versions currently pending review, including the assigned reviewer's GitHub username and assignment time. Requires module team permissions.
		 */
		get: operations['getTeamModulesPendingReview']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/v1/user/modules': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Get the authenticated user's modules
		 * @description Returns a list of modules the authenticated user is a maintainer of, including pending versions and latest published version info.
		 */
		get: operations['getUserModules']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
}
export type webhooks = Record<string, never>
export interface components {
	schemas: {
		ErrorResponse: {
			error: string
		}
		SubmitBuiltModuleInfo: {
			/**
			 * @description The type of module being submitted
			 * @enum {string}
			 */
			moduleType: 'companion-connection' | 'companion-surface'
			/** @description Name of the module */
			moduleName: string
			/** @description Url of build logs */
			logUrl?: string
			/** @description Url of built package and assets */
			pkgDirUrl: string
			/** @description Filename of built package */
			pkgName: string
			/** @description SHA256 hash of the package */
			pkgSha: string
			/** @description JSON string of the module manifest */
			manifestJson: string
		}
		/**
		 * @description Coarse classification of the SPDX licence declared in the module manifest, for consumers that can only redistribute modules under certain licences. `MIT` is the only category without redistribution constraints; `PERMISSIVE` covers other permissive licences (Apache-2.0, BSD, ISC and similar), `COPYLEFT` covers the GPL/AGPL/LGPL/MPL/EPL/CDDL families, and `UNKNOWN` means the licence string could not be matched to a known identifier.
		 * @enum {string}
		 */
		ModuleLicenseCategory: 'MIT' | 'PERMISSIVE' | 'COPYLEFT' | 'UNKNOWN'
		CompanionModuleInfo: {
			/** @description Id of the module */
			id: string
			/** @description The type of module */
			type: string
			/** @description Name of the module */
			name: string
			/** @description Short name of the module */
			shortname: string
			/** @description Manufacturer of the device controller by the module */
			manufacturer: string
			/** @description List of products supported by the module */
			products: string[]
			/** @description List of keywords for the module */
			keywords: string[]
			/** @description Url to the module store page */
			storeUrl: string
			/** @description Url to the module source code */
			githubUrl?: string
			/** @description Url to the module help markdown. This may reference other assets in the same folder */
			latestHelpUrl?: string
			/** @description The latest version number of the module */
			latestVersionNumber?: string
			/** @description Url to the module help markdown. This may reference other assets in the same folder */
			prereleaseHelpUrl?: string
			/** @description The latest prerelease version number of the module */
			prereleaseVersionNumber?: string
			/** @description Old module ids that this module replaces */
			legacyIds?: string[]
			/** @description Reason for deprecation (if deprecated) */
			deprecationReason?: string
			/** @description SPDX licence identifier declared by the latest package of this module */
			license: string | null
			licenseCategory: components['schemas']['ModuleLicenseCategory']
		}
		CompanionModuleVersionInfo: {
			/** @description Version number */
			id: string
			/** @description Whether this version is a prerelease */
			isPrerelease: boolean
			/** @description Whether this version is a legacy version (auto-translated to the modern module api) */
			isLegacy: boolean
			/** @description Unix timestamp when the version was published */
			releasedAt: number
			/** @description Url to the module tarball */
			tarUrl?: string
			/** @description SHA256 checksum of the tarball */
			tarSha?: string
			/** @description API version of the module */
			apiVersion: string
			/** @description Reason for deprecation (if deprecated) */
			deprecationReason?: string
			/** @description Url to the module help markdown. This may reference other assets in the same folder */
			helpUrl?: string
			/** @description SPDX licence identifier declared by this version's package */
			license: string | null
			licenseCategory: components['schemas']['ModuleLicenseCategory']
		}
		ButtonsModuleInfo: {
			/** @description Id of the module */
			id: string
			/** @description The type of module */
			type: string
			/** @description Name of the module */
			name: string
			/** @description Short name of the module */
			shortname: string
			/** @description Manufacturer of the device controller by the module */
			manufacturer: string
			/** @description List of products supported by the module */
			products: string[]
			/** @description List of keywords for the module */
			keywords: string[]
			/** @description Url to the module store page */
			storeUrl: string
			/** @description Url to the module source code */
			githubUrl?: string
			/** @description Url to the module help markdown. This may reference other assets in the same folder */
			latestHelpUrl?: string
			/** @description The latest version number of the module */
			latestVersionNumber?: string
			/** @description Old module ids that this module replaces */
			legacyIds?: string[]
			/** @description Reason for deprecation (if deprecated) */
			deprecationReason?: string
		}
		ButtonsModuleVersionInfo: {
			/** @description Version number */
			id: string
			/** @description Whether this version is a prerelease */
			isPrerelease: boolean
			/** @description Unix timestamp when the version was published */
			releasedAt: number
			/** @description Url to the module tarball */
			tarUrl?: string
			/** @description SHA256 checksum of the tarball */
			tarSha?: string
			/** @description API version of the module */
			apiVersion: string
			/** @description Reason for deprecation (if deprecated) */
			deprecationReason?: string
			/** @description Url to the module help markdown. This may reference other assets in the same folder */
			helpUrl?: string
		}
		WebsiteConnectionInfo: {
			/** @description Id of the module */
			id: string
			/** @description Version number */
			latestVersion: string
			/**
			 * Format: date-time
			 * @description When the latest module package was published
			 */
			packageUpdatedAt: string
			/** @description Name of the module */
			name: string
			/** @description Manufacturer of the device controller by the module */
			manufacturer: string
			/** @description List of products supported by the module */
			products: string[]
			/** @description List of keywords for the module */
			keywords: string[]
			/** @description List of authors of the module */
			authors: {
				name: string
				email?: string
			}[]
			/** @description Url to the module help markdown. This may reference other assets in the same folder */
			helpUrl?: string
			/** @description Blurb for the connection */
			blurb?: string | null
			/**
			 * @deprecated
			 * @description Deprecated: Use blurb instead
			 */
			blulb?: string | null
			/** @description Url to the company logo */
			companyLogo?: string | null
			/** @description Url to the company website */
			companyWebsite?: string | null
			/**
			 * @description The type of connection
			 * @enum {string}
			 */
			connectionType: 'COMMUNITY' | 'VENDOR' | 'VERIFIED' | 'PRO' | 'ELITE'
			/** @description Whether the connection is featured */
			isFeatured: boolean
			images: {
				url: string
				/**
				 * @deprecated
				 * @description Deprecated: All images are now of type PRODUCT
				 * @enum {string}
				 */
				type?: 'PRODUCT'
			}[]
			trainingVideos: {
				url: string
				title?: string | null
			}[]
			categories: {
				id: string
				name: string
			}[]
			/**
			 * Format: date-time
			 * @description When the connection was last updated (latest of module info changes and latest version publish date)
			 */
			updatedAt: string
		}
		WebsiteFeaturedConnectionInfo: components['schemas']['WebsiteConnectionInfo'] & {
			/** @description The order in which the connection is featured */
			featuredOrder: number
			/**
			 * Format: date-time
			 * @description When the connection was featured
			 */
			featuredAt?: string | null
			/**
			 * Format: date-time
			 * @description When the connection feature expires
			 */
			featuredExpiry?: string | null
		}
		PendingModuleVersionInfo: {
			/** @description Name of the module */
			moduleName: string
			/** @description Type of the module (e.g. companion-connection, companion-surface) */
			moduleType: string
			/** @description Git tag of the pending version */
			gitTag: string
			/** @description Unix timestamp (milliseconds) when the version was submitted */
			createdAt: number
		}
		TagInfo: {
			/** @description Unique identifier for the tag */
			id: string
			/** @description Display name of the tag */
			name: string
			/** @description URL to the tag icon image */
			icon?: string | null
		}
		PublicModuleListInfo: {
			/** @description Name of the module */
			name: string
			/** @description The type of module (e.g. companion-connection, companion-surface) */
			type: string
			/** @description Whether the module is deprecated */
			deprecated: boolean
			/**
			 * Format: date-time
			 * @description Date when the module was last published
			 */
			lastPublish?: string | null
			/** @description SPDX licence identifier declared by the latest package of this module */
			license: string | null
			licenseCategory: components['schemas']['ModuleLicenseCategory']
		}
		PublicPortalStats: {
			/** @description Number of active (non-deprecated) connection modules with a published version */
			connections: number
			/** @description Number of active (non-deprecated) surface modules with a published version */
			surfaces: number
			/** @description Number of approved (published) module versions */
			publishedVersions: number
		}
		PublicModuleDetailsInfo: {
			/** @description Reason for deprecation (if deprecated) */
			deprecationReason?: string | null
			/** @description Name of the successor module (if module was renamed/replaced) */
			successorName?: string | null
			/** @description Tags assigned to this module */
			assignedTags: components['schemas']['TagInfo'][]
			predecessors: {
				/** @description Id of the predecessor module */
				id: number
				/** @description Name of the predecessor module */
				name: string
				/** @description Type of the predecessor module */
				type: string
				/** @description Reason for deprecation of the predecessor */
				deprecationReason: string | null
			}[]
			/** @description SPDX licence identifier declared by the latest package of this module */
			license: string | null
			licenseCategory: components['schemas']['ModuleLicenseCategory']
		}
		PublicModuleVersionInfo: {
			/** @description Internal version id */
			id: number
			/** @description Git tag of the version */
			gitTag: string
			/** @description Whether this version is a prerelease */
			isPrerelease: boolean
			/** @description Current status of the version */
			status: string
			/** @description Whether this version has been published (has a package) */
			published: boolean
			/** @description URL to the published package tarball */
			packageUrl?: string | null
			/** @description URL to the HELP.md file for this version */
			helpUrl?: string | null
			/** @description URL to the build log */
			buildLogUrl?: string | null
			/** @description Reason for deprecation (if deprecated) */
			deprecationReason?: string | null
			/**
			 * Format: date-time
			 * @description When the version was created
			 */
			createdAt: string
			/** @description Tags assigned to this version */
			assignedTags: components['schemas']['TagInfo'][]
			/** @description SPDX licence identifier declared by this version's package, if it has one */
			license: string | null
			licenseCategory: components['schemas']['ModuleLicenseCategory']
		}
		TeamPendingModuleVersionInfo: components['schemas']['PendingModuleVersionInfo'] & {
			/** @description The assigned reviewer, if any */
			assignedReviewer?: {
				/** @description GitHub username of the assigned reviewer */
				githubUsername: string | null
				/** @description Unix timestamp (milliseconds) when the reviewer was assigned */
				assignedAt: number
			} | null
		}
		UserModuleInfo: {
			/** @description Name of the module */
			name: string
			/** @description Type of the module (e.g. companion-connection, companion-surface) */
			type: string
			latestPublished?: {
				/** @description Version string of the latest published package */
				version: string
				/**
				 * Format: date-time
				 * @description When the latest package was published
				 */
				createdAt: string
			} | null
			pendingVersions: {
				/** @description Internal version id */
				id?: number
				/** @description Git tag of the pending version */
				gitTag: string
				/**
				 * Format: date-time
				 * @description When the version was submitted
				 */
				createdAt: string
			}[]
		}
	}
	responses: never
	parameters: never
	requestBodies: never
	headers: never
	pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
	putModulePackage: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['SubmitBuiltModuleInfo']
			}
		}
		responses: {
			/** @description successful operation */
			200: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description failed operation */
			400: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ErrorResponse']
				}
			}
		}
	}
	getWebsiteConnections: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description successful operation */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': {
						connections: components['schemas']['WebsiteConnectionInfo'][]
						/**
						 * Format: date-time
						 * @description When the connections list was last updated
						 */
						updatedAt: string
					}
				}
			}
		}
	}
	getWebsiteFeaturedConnections: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description successful operation */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': {
						connections: components['schemas']['WebsiteFeaturedConnectionInfo'][]
						/**
						 * Format: date-time
						 * @description When the featured connections list was last updated
						 */
						updatedAt: string
					}
				}
			}
		}
	}
	getCompanionModules: {
		parameters: {
			query?: {
				/** @description Limit versions included in results to those compatible with the given API version */
				'module-api-version'?: string[]
			}
			header?: never
			path: {
				/** @description Type of module to get */
				moduleType: 'connection' | 'surface'
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description successful operation */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': {
						modules: components['schemas']['CompanionModuleInfo'][]
					}
				}
			}
		}
	}
	getCompanionModuleVersions: {
		parameters: {
			query?: never
			header?: never
			path: {
				/** @description Name of module to get */
				moduleType: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description successful operation */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': {
						versions: components['schemas']['CompanionModuleVersionInfo'][]
					}
				}
			}
			/** @description Module not found */
			404: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ErrorResponse']
				}
			}
		}
	}
	getButtonsModules: {
		parameters: {
			query?: {
				/** @description Limit versions included in results to those compatible with the given API version */
				'module-api-version'?: string[]
			}
			header?: never
			path: {
				/** @description Type of module to get */
				moduleType: 'connection'
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description successful operation */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': {
						modules: components['schemas']['ButtonsModuleInfo'][]
					}
				}
			}
		}
	}
	getButtonsModuleVersions: {
		parameters: {
			query?: never
			header?: never
			path: {
				/** @description Name of module to get */
				moduleType: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description successful operation */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': {
						versions: components['schemas']['ButtonsModuleVersionInfo'][]
					}
				}
			}
			/** @description Module not found */
			404: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ErrorResponse']
				}
			}
		}
	}
	getPublicModules: {
		parameters: {
			query?: never
			header?: never
			path: {
				/** @description Type of module to get */
				moduleType: 'companion-connection' | 'companion-surface'
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description successful operation */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': {
						modules: components['schemas']['PublicModuleListInfo'][]
					}
				}
			}
		}
	}
	getPublicModuleDetails: {
		parameters: {
			query?: never
			header?: never
			path: {
				/** @description Type of module to get */
				moduleType: 'companion-connection' | 'companion-surface'
				/** @description Name of module to get */
				moduleName: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description successful operation */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['PublicModuleDetailsInfo']
				}
			}
			/** @description Module not found */
			404: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ErrorResponse']
				}
			}
		}
	}
	getPublicModuleVersions: {
		parameters: {
			query?: never
			header?: never
			path: {
				/** @description Type of module to get */
				moduleType: 'companion-connection' | 'companion-surface'
				/** @description Name of module to get */
				moduleName: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description successful operation */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': {
						versions: components['schemas']['PublicModuleVersionInfo'][]
					}
				}
			}
			/** @description Module not found */
			404: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ErrorResponse']
				}
			}
		}
	}
	getPublicStats: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description successful operation */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['PublicPortalStats']
				}
			}
		}
	}
	getModulesPendingReview: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description successful operation */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': {
						versions: components['schemas']['PendingModuleVersionInfo'][]
					}
				}
			}
		}
	}
	getTeamModulesPendingReview: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description successful operation */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': {
						versions: components['schemas']['TeamPendingModuleVersionInfo'][]
					}
				}
			}
			/** @description unauthorized */
			401: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ErrorResponse']
				}
			}
			/** @description forbidden - requires module team permissions */
			403: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ErrorResponse']
				}
			}
		}
	}
	getUserModules: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description successful operation */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': {
						modules: components['schemas']['UserModuleInfo'][]
					}
				}
			}
			/** @description unauthorized */
			401: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ErrorResponse']
				}
			}
		}
	}
}
