enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 3d

npmPreapprovedPackages:
  - "@companion-app/*"
  - "@companion-module/*"
  - "@companion-surface/*"
  - "@julusian/*"
  - node-hid
  - typescript
  - "@typescript/*"

plugins:
  # yarns pnp patching of typescript doesn't work
  - path: .yarn/plugins/plugin-disable-typescript-compat.cjs
    spec: "plugin-disable-typescript-compat"
