nodeLinker: node-modules

npmMinimalAgeGate: 3d

npmPreapprovedPackages:
  - "@companion-app/*"
  - "@companion-module/*"
  - "@companion-surface/*"

# Disable postinstall scripts. Any packages which need it can be enabled individually with dependenciesMeta in package.json
enableScripts: false
