/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Companion Link protocol payload definitions. Each $def is a message payload type identified by its message type string. Protocol.ts composes these into discriminated-union message envelopes.
 */
export interface LinkProtocolPayloads {
	/**
	 * Reference anchor — ensures all $defs are reachable and generated as TypeScript interfaces.
	 */
	_payloads?: {
		announcement?: LinkAnnouncementPayload
		subscribeRequest?: LinkSubscribeRequestPayload
		subscribeResponse?: LinkSubscribeResponsePayload
		unsubscribeRequest?: LinkUnsubscribeRequestPayload
		buttonCommand?: LinkButtonCommandPayload
		buttonUpdate?: LinkButtonUpdatePayload
		buttonLocation?: LinkButtonLocation
		buttonLocationWithResolution?: LinkButtonLocationWithResolution
		subscribeResponseButtonState?: LinkSubscribeResponseButtonState
		gridSize?: LinkGridSize
	}
}
/**
 * Discovery announcement from a Companion instance.
 */
export interface LinkAnnouncementPayload {
	/**
	 * Unique instance UUID.
	 */
	id: string
	/**
	 * Human-readable instance name.
	 */
	name: string
	/**
	 * Companion application version string.
	 */
	version: string
	/**
	 * Link protocol version number.
	 */
	protocolVersion: number
	/**
	 * Number of pages configured on this instance.
	 */
	pageCount: number
	gridSize: LinkGridSize
	/**
	 * Unix timestamp in milliseconds.
	 */
	timestamp: number
}
/**
 * Grid dimensions for an instance.
 */
export interface LinkGridSize {
	/**
	 * Number of rows in the grid.
	 */
	rows: number
	/**
	 * Number of columns in the grid.
	 */
	cols: number
}
/**
 * Request to subscribe to button state updates at specific resolutions.
 */
export interface LinkSubscribeRequestPayload {
	/**
	 * List of buttons and their requested resolutions.
	 */
	buttons: LinkButtonLocationWithResolution[]
	/**
	 * Unix timestamp in milliseconds.
	 */
	timestamp: number
}
/**
 * A button location with a requested bitmap resolution.
 */
export interface LinkButtonLocationWithResolution {
	/**
	 * Page number.
	 */
	page: number
	/**
	 * Row number.
	 */
	row: number
	/**
	 * Column number.
	 */
	col: number
	/**
	 * Requested bitmap width in pixels.
	 */
	width: number
	/**
	 * Requested bitmap height in pixels.
	 */
	height: number
}
/**
 * Response containing initial state for subscribed buttons.
 */
export interface LinkSubscribeResponsePayload {
	/**
	 * List of initial button states.
	 */
	states: LinkSubscribeResponseButtonState[]
	/**
	 * Unix timestamp in milliseconds.
	 */
	timestamp: number
}
/**
 * Initial state for a subscribed button.
 */
export interface LinkSubscribeResponseButtonState {
	/**
	 * Page number.
	 */
	page: number
	/**
	 * Row number.
	 */
	row: number
	/**
	 * Column number.
	 */
	col: number
	/**
	 * Bitmap width in pixels.
	 */
	width: number
	/**
	 * Bitmap height in pixels.
	 */
	height: number
	/**
	 * PNG data URL at the requested resolution, or null if no render is available.
	 */
	dataUrl: string | null
	/**
	 * Whether the button is currently pressed.
	 */
	pressed: boolean
	/**
	 * Ordered list of instance UUIDs this button image has passed through, for loop detection.
	 */
	sourceChain: string[]
}
/**
 * Request to unsubscribe from button state updates.
 */
export interface LinkUnsubscribeRequestPayload {
	/**
	 * List of buttons and resolutions to unsubscribe from.
	 */
	buttons: LinkButtonLocationWithResolution[]
	/**
	 * Unix timestamp in milliseconds.
	 */
	timestamp: number
}
/**
 * Payload for button press or release commands.
 */
export interface LinkButtonCommandPayload {
	/**
	 * Page number.
	 */
	page: number
	/**
	 * Row number.
	 */
	row: number
	/**
	 * Column number.
	 */
	col: number
	/**
	 * Unix timestamp in milliseconds.
	 */
	timestamp: number
}
/**
 * Combined bitmap and state update for a subscribed button at a specific resolution.
 */
export interface LinkButtonUpdatePayload {
	/**
	 * Page number.
	 */
	page: number
	/**
	 * Row number.
	 */
	row: number
	/**
	 * Column number.
	 */
	col: number
	/**
	 * Bitmap width in pixels.
	 */
	width: number
	/**
	 * Bitmap height in pixels.
	 */
	height: number
	/**
	 * PNG data URL at the subscribed resolution.
	 */
	dataUrl: string
	/**
	 * Whether the button is currently pressed.
	 */
	pressed: boolean
	/**
	 * Ordered list of instance UUIDs this button image has passed through, for loop detection. The publishing instance appends its own UUID before sending.
	 */
	sourceChain: string[]
	/**
	 * Unix timestamp in milliseconds.
	 */
	timestamp: number
}
/**
 * Identifies a button by its page, row, and column.
 */
export interface LinkButtonLocation {
	/**
	 * Page number.
	 */
	page: number
	/**
	 * Row number.
	 */
	row: number
	/**
	 * Column number.
	 */
	col: number
}
