name: Bug report
description: Create a bug report to help us improve.
labels:
  - BUG
title: '[BUG]'
body:
  - type: markdown
    attributes:
      value: |
        **Make sure you're on the latest bleeding edge build**
        *Before you report a bug, make sure you're not reporting something that have been fixed in the master branch by downloading a "latest" build from https://builds.bitfocus.io/companion/*

        **This form is only for bugs related to the Companion software itself. If you are reporting a bug that you feel is limited to a specific Companion module, please make the bug report directly in that module's repository.** Most Repositories can be located within the Bitfocus Github account (https://github.com/bitfocus?type=source) with the following naming convention: companion-module-*manufacturer*-*product*
  - type: checkboxes
    attributes:
      label: Is this a bug in companion itself or a module?
      description: If you wish to report a bug in a module, please do so against the correct repository found at https://github.com/bitfocus?type=source
      options:
        - label: I believe this to be a bug in companion
          required: true
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. Screenshots are always helpful to understand the problem.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment (please complete the following information)
      description: |
        examples:
          - **OS**: Windows 10
          - **Browser**: Chrome 94
          - **Companion Version**: 2.2.0-b177f8fb-3722
      value: |
        - OS:
        - Browser:
        - Companion Version:
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
