export const MAX_MODULE_TAR_SIZE = 1024 * 1024 * 20 // 20MB
export const MAX_DECOMPRESSED_MODULE_TAR_SIZE = MAX_MODULE_TAR_SIZE * 5 // 100MB
export const MAX_MODULE_BUNDLE_TAR_SIZE = 1024 * 1024 * 500 // 500MB. This is small enough that it can be kept in memory
export const MAX_DECOMPRESSED_MODULE_BUNDLE_TAR_SIZE = MAX_MODULE_BUNDLE_TAR_SIZE * 4 // 2GB
