/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema describing a satellite surface layout: default styling and a map of controls with positions and optional style overrides.
 */
export interface SatelliteSurfaceLayout {
	/**
	 * Named collection of style presets. The preset named `default` is required and is used as the fallback style for controls when no `stylePreset` is specified.
	 */
	stylePresets: {
		default: SatelliteControlStylePreset
		[k: string]: SatelliteControlStylePreset
	}
	controls: {
		[k: string]: SatelliteControlDefinition
	}
}
/**
 * Styling options that can be applied to controls. Can be used as the default style or as per-control overrides.
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^.+$".
 */
export interface SatelliteControlStylePreset {
	bitmap?: SatelliteConfigSize
	/**
	 * If true, the control requests text to be reported.
	 */
	text?: boolean
	/**
	 * If true, the control requests text style properties to be reported
	 */
	textStyle?: boolean
	/**
	 * If set, the control requests colours to be reported.
	 */
	colors?: 'hex' | 'rgb'
	leds?: SatelliteLedsConfig
}
/**
 * If set, bitmaps of the specified size will be reported.
 */
export interface SatelliteConfigSize {
	/**
	 * Width in pixels (non-negative).
	 */
	w: number
	/**
	 * Height in pixels (non-negative).
	 */
	h: number
}
/**
 * If set, the control has an addressable strip/ring of LEDs and requests LED colours to be reported.
 */
export interface SatelliteLedsConfig {
	/**
	 * The number of individually addressable LED segments.
	 */
	segments: number
	/**
	 * How Companion maps a gauge onto these LEDs. `full-ring`: the LEDs form a complete circle and the gauge is rendered faithfully (angles, deadzone and colours respected 1:1); segment 0 is at 6 o'clock and indices increase clockwise. `simple`: any other shape where the value is swept across all segments, with segment 0 as the 0% end. In both cases the surface re-maps to its physical wiring locally if it differs from these conventions.
	 */
	mode: 'full-ring' | 'simple'
}
/**
 * Single control definition. The id must be unique and may be user facing in logs. Typically the id would be in the form of 1/0, matching the row/column of the control.
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^[a-zA-Z0-9\-\/]+$".
 */
export interface SatelliteControlDefinition {
	/**
	 * Zero-based row index for layout placement.
	 */
	row: number
	/**
	 * Zero-based column index for layout placement.
	 */
	column: number
	/**
	 * Optional name of a style preset defined in `stylePresets`. If present, the control will use the named preset instead of the default style.
	 */
	stylePreset?: string
}
