/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema describing a satellite surface layout: default styling and a map of controls with positions and optional style overrides.
 */
export interface SatelliteSurfaceLayout {
	/**
	 * Named collection of style presets. The preset named `default` is required and is used as the fallback style for controls when no `stylePreset` is specified.
	 */
	stylePresets?: {
		default: SatelliteControlStylePreset
		[k: string]: SatelliteControlStylePreset
	}
	controls: {
		/**
		 * Single control definition. The id must be unique and may be user facing in logs. Typically the id would be in the form of 1/0, matching the row/column of the control.
		 *
		 * This interface was referenced by `undefined`'s JSON-Schema definition
		 * via the `patternProperty` "^[a-zA-Z0-9\-\/]+$".
		 */
		[k: string]: {
			/**
			 * Zero-based row index for layout placement.
			 */
			row: number
			/**
			 * Zero-based column index for layout placement.
			 */
			column: number
			/**
			 * Optional name of a style preset defined in `stylePresets`. If present, the control will use the named preset instead of the default style.
			 */
			stylePreset?: string
		}
	}
}
/**
 * Styling options that can be applied to controls. Can be used as the default style or as per-control overrides.
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^.+$".
 */
export interface SatelliteControlStylePreset {
	bitmap?: SatelliteConfigSize
	/**
	 * If true, the control should display text in addition to any bitmap.
	 */
	text?: boolean
	/**
	 * If true, apply the control's text styling (font-size, weight, etc.). If false or absent, text is displayed with no additional styling.
	 */
	textStyle?: boolean
	/**
	 * If true, the control supports color selection or multiple color states.
	 */
	colors?: boolean
}
/**
 * Optional bitmap size used when rendering an image for the control.
 */
export interface SatelliteConfigSize {
	/**
	 * Width in pixels (non-negative).
	 */
	w: number
	/**
	 * Height in pixels (non-negative).
	 */
	h: number
}
