/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ConfigField = StaticTextField | TextInputField | DropdownField | NumberField | CheckboxField
export type StaticTextField = CommonFields & {
	type: 'static-text'
	/**
	 * Static text content to display.
	 */
	value: string
	[k: string]: unknown
}
export type TextInputField = CommonFields & {
	type: 'textinput'
	/**
	 * Default value.
	 */
	default?: string
	/**
	 * Optional regex pattern the value must match.
	 */
	regex?: string
	/**
	 * Whether the input is a multiline text area.
	 */
	multiline?: boolean
	[k: string]: unknown
}
export type DropdownField = CommonFields & {
	type: 'dropdown'
	/**
	 * List of selectable choices.
	 *
	 * @minItems 1
	 */
	choices: [DropdownChoice, ...DropdownChoice[]]
	/**
	 * Default selected choice id.
	 */
	default?: string | number
	/**
	 * Whether the user can type a custom value not in the choices list.
	 */
	allowCustom?: boolean
	[k: string]: unknown
}
export type NumberField = CommonFields & {
	type: 'number'
	/**
	 * Minimum allowed value.
	 */
	min: number
	/**
	 * Maximum allowed value.
	 */
	max: number
	/**
	 * Default value.
	 */
	default?: number
	/**
	 * Step increment for the input.
	 */
	step?: number
	[k: string]: unknown
}
export type CheckboxField = CommonFields & {
	type: 'checkbox'
	/**
	 * Default checked state.
	 */
	default?: boolean
	[k: string]: unknown
}
/**
 * Schema describing an array of custom config field definitions for a satellite device. These fields are rendered in the Companion UI surface settings panel and the stored values are pushed back to the device via DEVICE-CONFIG.
 */
export type SatelliteConfigFields = ConfigField[]

export interface CommonFields {
	/**
	 * Unique identifier for the field. Used as the key in the DEVICE-CONFIG JSON object.
	 */
	id: string
	/**
	 * Human-readable label shown in the UI.
	 */
	label: string
	/**
	 * Optional longer description shown in the UI to explain the field.
	 */
	description?: string
	/**
	 * Optional tooltip text shown on hover.
	 */
	tooltip?: string
	/**
	 * Optional expression that controls field visibility. When provided, the field is only shown when the expression evaluates to true.
	 */
	isVisibleExpression?: string
	[k: string]: unknown
}
export interface DropdownChoice {
	/**
	 * The value stored when this choice is selected.
	 */
	id: string | number
	/**
	 * Human-readable label for the choice.
	 */
	label: string
}
