/* eslint-disable */
// This file is autogenerated by tools/generate_graphics_types.mts

import type { ExpressionOrValue } from '../Model/Expression.js'
import type { ButtonGraphicsElementUsage, ButtonGraphicsDecorationType, HorizontalAlignment, VerticalAlignment } from './StyleModel.js'

export interface ButtonGraphicsDrawBase {
	readonly id: string
	usage: ButtonGraphicsElementUsage
	enabled: boolean
	opacity: number
}

export interface ButtonGraphicsElementBase {
	readonly id: string
	name: string
	usage: ButtonGraphicsElementUsage
	enabled: ExpressionOrValue<boolean>
	opacity: ExpressionOrValue<number>
}

export interface ButtonGraphicsDrawBounds {
	x: number
	y: number
	width: number
	height: number
}

export interface ButtonGraphicsBounds {
	x: ExpressionOrValue<number>
	y: ExpressionOrValue<number>
	width: ExpressionOrValue<number>
	height: ExpressionOrValue<number>
}

export interface ButtonGraphicsCanvasDrawElement extends Omit<ButtonGraphicsDrawBase, 'enabled' | 'opacity'> {
	// Note: this is the background element and can only be at the bottom of the stack
	type: 'canvas'
	decoration: ButtonGraphicsDecorationType // replaces show_topbar
}

export interface ButtonGraphicsCanvasElement extends Omit<ButtonGraphicsElementBase, 'enabled' | 'opacity'> {
	// Note: this is the background element and can only be at the bottom of the stack
	type: 'canvas'
	decoration: ExpressionOrValue<ButtonGraphicsDecorationType> // replaces show_topbar
}

export interface ButtonGraphicsTextDrawElement extends ButtonGraphicsDrawBase, ButtonGraphicsDrawBounds {
	type: 'text'
	text: string
	fontsize: string
	color: number
	outlineColor: number
	halign: HorizontalAlignment
	valign: VerticalAlignment
}

export interface ButtonGraphicsTextElement extends ButtonGraphicsElementBase, ButtonGraphicsBounds {
	type: 'text'
	text: ExpressionOrValue<string>
	fontsize: ExpressionOrValue<string>
	color: ExpressionOrValue<number>
	outlineColor: ExpressionOrValue<number>
	halign: ExpressionOrValue<HorizontalAlignment>
	valign: ExpressionOrValue<VerticalAlignment>
}

export interface ButtonGraphicsImageDrawElement extends ButtonGraphicsDrawBase, ButtonGraphicsDrawBounds {
	type: 'image'
	base64Image: string | null
	halign: HorizontalAlignment
	valign: VerticalAlignment
	fillMode: "fit_or_shrink" | "fit" | "fill" | "crop"
}

export interface ButtonGraphicsImageElement extends ButtonGraphicsElementBase, ButtonGraphicsBounds {
	type: 'image'
	base64Image: ExpressionOrValue<string | null>
	halign: ExpressionOrValue<HorizontalAlignment>
	valign: ExpressionOrValue<VerticalAlignment>
	fillMode: ExpressionOrValue<"fit_or_shrink" | "fit" | "fill" | "crop">
}

export interface ButtonGraphicsBoxDrawElement extends ButtonGraphicsDrawBase, ButtonGraphicsDrawBounds {
	type: 'box'
	color: number
	borderWidth: number
	borderColor: number
	borderPosition: "inside" | "center" | "outside"
}

export interface ButtonGraphicsBoxElement extends ButtonGraphicsElementBase, ButtonGraphicsBounds {
	type: 'box'
	color: ExpressionOrValue<number>
	borderWidth: ExpressionOrValue<number>
	borderColor: ExpressionOrValue<number>
	borderPosition: ExpressionOrValue<"inside" | "center" | "outside">
}

export interface ButtonGraphicsLineDrawElement extends ButtonGraphicsDrawBase {
	type: 'line'
	fromX: number
	fromY: number
	toX: number
	toY: number
	borderWidth: number
	borderColor: number
	borderPosition: "inside" | "center" | "outside"
}

export interface ButtonGraphicsLineElement extends ButtonGraphicsElementBase {
	type: 'line'
	fromX: ExpressionOrValue<number>
	fromY: ExpressionOrValue<number>
	toX: ExpressionOrValue<number>
	toY: ExpressionOrValue<number>
	borderWidth: ExpressionOrValue<number>
	borderColor: ExpressionOrValue<number>
	borderPosition: ExpressionOrValue<"inside" | "center" | "outside">
}

export interface ButtonGraphicsGroupDrawElement extends ButtonGraphicsDrawBase, ButtonGraphicsDrawBounds {
	type: 'group'
	children: SomeButtonGraphicsDrawElement[]
}

export interface ButtonGraphicsGroupElement extends ButtonGraphicsElementBase, ButtonGraphicsBounds {
	type: 'group'
	children: SomeButtonGraphicsElement[]
}

export type SomeButtonGraphicsDrawElement =
	| ButtonGraphicsCanvasDrawElement
	| ButtonGraphicsTextDrawElement
	| ButtonGraphicsImageDrawElement
	| ButtonGraphicsBoxDrawElement
	| ButtonGraphicsLineDrawElement
	| ButtonGraphicsGroupDrawElement

export type SomeButtonGraphicsElement =
	| ButtonGraphicsCanvasElement
	| ButtonGraphicsTextElement
	| ButtonGraphicsImageElement
	| ButtonGraphicsBoxElement
	| ButtonGraphicsLineElement
	| ButtonGraphicsGroupElement
