/* eslint-disable */
// This file is autogenerated by tools/generate_graphics_types.mts

import type { ExpressionOrValue } from '../Model/Expression.js'
import type {
	ButtonGraphicsElementUsage,
	ButtonGraphicsDecorationType,
	HorizontalAlignment,
	VerticalAlignment,
	CompositeElementOptionKey,
} from './StyleModel.js'

export interface ButtonGraphicsDrawBase {
	readonly id: string
	usage: ButtonGraphicsElementUsage
	enabled: boolean
	opacity: number
}

export interface ButtonGraphicsElementBase {
	readonly id: string
	name: string
	usage: ButtonGraphicsElementUsage
	enabled: ExpressionOrValue<boolean>
	opacity: ExpressionOrValue<number>
}

export interface ButtonGraphicsDrawBounds {
	x: number
	y: number
	width: number
	height: number
}

export interface ButtonGraphicsBounds {
	x: ExpressionOrValue<number>
	y: ExpressionOrValue<number>
	width: ExpressionOrValue<number>
	height: ExpressionOrValue<number>
}

export interface ButtonGraphicsDrawBorder {
	borderWidth: number
	borderColor: number
	borderPosition: 'inside' | 'center' | 'outside'
}

export interface ButtonGraphicsBorder {
	borderWidth: ExpressionOrValue<number>
	borderColor: ExpressionOrValue<number>
	borderPosition: ExpressionOrValue<'inside' | 'center' | 'outside'>
}

export interface ButtonGraphicsDrawRotation {
	rotation: number
}

export interface ButtonGraphicsRotation {
	rotation: ExpressionOrValue<number>
}

export interface ButtonGraphicsCanvasDrawElement extends Omit<ButtonGraphicsDrawBase, 'enabled' | 'opacity'> {
	// Note: this is the background element and can only be at the bottom of the stack
	type: 'canvas'
	decoration: ButtonGraphicsDecorationType // replaces show_topbar
}

export interface ButtonGraphicsCanvasElement extends Omit<ButtonGraphicsElementBase, 'enabled' | 'opacity'> {
	// Note: this is the background element and can only be at the bottom of the stack
	type: 'canvas'
	decoration: ExpressionOrValue<ButtonGraphicsDecorationType> // replaces show_topbar
}

export interface ButtonGraphicsTextDrawElement
	extends ButtonGraphicsDrawBase, ButtonGraphicsDrawBounds, ButtonGraphicsDrawRotation {
	type: 'text'
	text: string
	fontsize: string
	color: number
	outlineColor: number
	halign: HorizontalAlignment
	valign: VerticalAlignment
}

export interface ButtonGraphicsTextElement
	extends ButtonGraphicsElementBase, ButtonGraphicsBounds, ButtonGraphicsRotation {
	type: 'text'
	text: ExpressionOrValue<string>
	fontsize: ExpressionOrValue<string>
	color: ExpressionOrValue<number>
	outlineColor: ExpressionOrValue<number>
	halign: ExpressionOrValue<HorizontalAlignment>
	valign: ExpressionOrValue<VerticalAlignment>
}

export interface ButtonGraphicsImageDrawElement
	extends ButtonGraphicsDrawBase, ButtonGraphicsDrawBounds, ButtonGraphicsDrawRotation {
	type: 'image'
	base64Image: string | null
	halign: HorizontalAlignment
	valign: VerticalAlignment
	fillMode: 'fit_or_shrink' | 'fit' | 'fill' | 'crop'
}

export interface ButtonGraphicsImageElement
	extends ButtonGraphicsElementBase, ButtonGraphicsBounds, ButtonGraphicsRotation {
	type: 'image'
	base64Image: ExpressionOrValue<string | null>
	halign: ExpressionOrValue<HorizontalAlignment>
	valign: ExpressionOrValue<VerticalAlignment>
	fillMode: ExpressionOrValue<'fit_or_shrink' | 'fit' | 'fill' | 'crop'>
}

export interface ButtonGraphicsBoxDrawElement
	extends ButtonGraphicsDrawBase, ButtonGraphicsDrawBounds, ButtonGraphicsDrawBorder, ButtonGraphicsDrawRotation {
	type: 'box'
	color: number
}

export interface ButtonGraphicsBoxElement
	extends ButtonGraphicsElementBase, ButtonGraphicsBounds, ButtonGraphicsBorder, ButtonGraphicsRotation {
	type: 'box'
	color: ExpressionOrValue<number>
}

export interface ButtonGraphicsLineDrawElement extends ButtonGraphicsDrawBase {
	type: 'line'
	fromX: number
	fromY: number
	toX: number
	toY: number
	borderWidth: number
	borderColor: number
	borderPosition: 'inside' | 'center' | 'outside'
}

export interface ButtonGraphicsLineElement extends ButtonGraphicsElementBase {
	type: 'line'
	fromX: ExpressionOrValue<number>
	fromY: ExpressionOrValue<number>
	toX: ExpressionOrValue<number>
	toY: ExpressionOrValue<number>
	borderWidth: ExpressionOrValue<number>
	borderColor: ExpressionOrValue<number>
	borderPosition: ExpressionOrValue<'inside' | 'center' | 'outside'>
}

export interface ButtonGraphicsGroupDrawElement
	extends ButtonGraphicsDrawBase, ButtonGraphicsDrawBounds, ButtonGraphicsDrawRotation {
	type: 'group'
	children: SomeButtonGraphicsDrawElement[]
}

export interface ButtonGraphicsGroupElement
	extends ButtonGraphicsElementBase, ButtonGraphicsBounds, ButtonGraphicsRotation {
	type: 'group'
	children: SomeButtonGraphicsElement[]
}

export interface ButtonGraphicsCircleDrawElement
	extends ButtonGraphicsDrawBase, ButtonGraphicsDrawBounds, ButtonGraphicsDrawBorder {
	type: 'circle'
	color: number
	startAngle: number
	endAngle: number
	drawSlice: boolean
	borderOnlyArc: boolean
}

export interface ButtonGraphicsCircleElement
	extends ButtonGraphicsElementBase, ButtonGraphicsBounds, ButtonGraphicsBorder {
	type: 'circle'
	color: ExpressionOrValue<number>
	startAngle: ExpressionOrValue<number>
	endAngle: ExpressionOrValue<number>
	drawSlice: ExpressionOrValue<boolean>
	borderOnlyArc: ExpressionOrValue<boolean>
}

export interface ButtonGraphicsCompositeElement extends ButtonGraphicsElementBase, ButtonGraphicsBounds {
	type: 'composite'
	connectionId: string
	elementId: string

	/**
	 * Custom elements have options defined by their composite definition
	 */
	[customKey: CompositeElementOptionKey]: ExpressionOrValue<any> | undefined
}

export type SomeButtonGraphicsDrawElement =
	| ButtonGraphicsCanvasDrawElement
	| ButtonGraphicsTextDrawElement
	| ButtonGraphicsImageDrawElement
	| ButtonGraphicsBoxDrawElement
	| ButtonGraphicsLineDrawElement
	| ButtonGraphicsGroupDrawElement
	| ButtonGraphicsCircleDrawElement

export type SomeButtonGraphicsElement =
	| ButtonGraphicsCanvasElement
	| ButtonGraphicsTextElement
	| ButtonGraphicsImageElement
	| ButtonGraphicsBoxElement
	| ButtonGraphicsLineElement
	| ButtonGraphicsGroupElement
	| ButtonGraphicsCircleElement
	| ButtonGraphicsCompositeElement
