#!/usr/bin/env tsx

/**
 * Generate the user-guide "Configuration reference" page from the single source of truth for
 * launch options (shared-lib LAUNCH_OPTIONS) plus the config-tool presentation metadata.
 *
 * This keeps the docs from drifting: the config.yaml keys, defaults, cli flags and env vars are
 * exactly what the server accepts and the config-tool reads/writes. Run via `yarn build:config-reference`.
 *
 * Note: this imports config-tool/lib/presentation.ts, which resolves `@companion-app/shared` to its
 * built `dist`, so shared-lib must be built first (run `yarn build:ts`). It is intentionally NOT part
 * of `postinstall` for that reason.
 */
import { fileURLToPath } from 'url'
import { $, fs } from 'zx'
import { assertPresentationComplete, PAGE_ORDER, PRESENTATION } from '../config-tool/lib/presentation.ts'
import { LAUNCH_OPTIONS, launchOptionFlagName, type LaunchOption } from '../shared-lib/lib/LaunchOptions.ts'

// Fail loudly if a launch option is missing presentation metadata, rather than silently
// emitting an incomplete reference.
assertPresentationComplete()

/** Server-only cli flags declared directly in companion/lib/main.ts (not managed by the config file). */
const SERVER_ONLY_FLAGS: ReadonlyArray<{ flag: string; description: string }> = [
	{
		flag: '--config-dir <path>',
		description: 'Directory used to store configuration and data. The default varies by platform.',
	},
	{
		flag: '--list-interfaces',
		description: 'List the available network interfaces that can be used for the admin bind interface, then exit.',
	},
]

/** Escape a value so it is safe inside a markdown table cell. */
function cell(value: string): string {
	return value
		.replace(/\|/g, '\\|')
		.replace(/\s*\n\s*/g, ' ')
		.trim()
}

/** A compact one-line summary of an option's type, default, cli flag and env var. */
function metaLine(option: LaunchOption): string {
	const parts: string[] = []
	if (option.type === 'enum' && option.enumValues) {
		parts.push(`one of ${option.enumValues.map((v) => `\`${v}\``).join(', ')}`)
	} else {
		parts.push(`\`${option.type}\``)
	}
	if (option.default !== undefined) parts.push(`default \`${String(option.default)}\``)
	const flag = launchOptionFlagName(option)
	if (flag) parts.push(`cli \`${flag}\``)
	if (option.envVar) parts.push(`env \`${option.envVar}\``)
	return parts.join(' · ')
}

let md = `---
title: Configuration reference
sidebar_label: Configuration reference
sidebar_position: 4
slug: config-reference
description: Every launch option Companion accepts - config.yaml keys, defaults, environment variables and cli flags.
---

{/* DO NOT EDIT - this page is generated by tools/generate_config_reference.mts. Run \`yarn build:config-reference\`. */}

# Configuration reference

This is the complete list of the launch options that control how the Companion server starts.

On a **headless or Docker install** these are set in a \`config.yaml\` file (\`/companion/config.yaml\` in the
Docker image, \`/etc/companion/config.yaml\` on CompanionPi), using the key in the **Key** column below. On
CompanionPi the [config-tool](./companion-pi/config-tool.md) edits this file for you; in the Docker image you
edit it by hand and the entrypoint applies it on startup. The same options can be passed as **cli flags** or
**environment variables** when running the server manually.

For guidance on _what_ these do and when to change them, see [Server configuration](./server-configuration.md).

`

for (const page of PAGE_ORDER) {
	const options = LAUNCH_OPTIONS.filter((option) => PRESENTATION[option.key]?.page === page)
	if (options.length === 0) continue

	md += `## ${page}\n\n`
	for (const option of options) {
		const presentation = PRESENTATION[option.key]
		md += `### \`${option.key}\`\n\n`
		md += `${metaLine(option)}\n\n`
		md += `${cell(presentation.help)}\n\n`
	}
}

md += `## Server-only options\n\n`
md += `These are set by the launcher or container entrypoint rather than the \`config.yaml\` file, so they are only available as cli flags.\n\n`
for (const { flag, description } of SERVER_ONLY_FLAGS) {
	md += `- \`${flag}\` — ${cell(description)}\n`
}
md += `\n`

const outputPath = new URL('../docs/user-guide/1_getting-started/config-reference.generated.md', import.meta.url)
await fs.writeFile(outputPath, md, 'utf8')
await $`prettier --write ${fileURLToPath(outputPath)}`

console.log(`Wrote ${fileURLToPath(outputPath)}`)
